using DynamicData;
using Mutagen.Bethesda;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.WPF.Reflection.Attributes;
using Noggog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace GenderDialoguePatch
{
    public class TestSettings
    {
        [SettingName("Patch Book Text")]
        [Tooltip("Patches book text to refer to the player using they/them, or custom pronouns if they are enabled")]
        public bool PatchBookText = true;

        [SettingName("Custom Pronouns")]
        public bool PatchCustomPronouns = false;

        [SettingName("Nominative")]
        public string CustomPronoun_Nominative = "they";

        [SettingName("Accusative")]
        public string CustomPronoun_Accusative = "them";

        [SettingName("Pronominal Possessive")]
        public string CustomPronoun_PronominalPossessive = "their";

        [SettingName("Predicative Possessive")]
        public string CustomPronoun_PredicativePossessive = "theirs";

        [SettingName("Reflexive")]
        public string CustomPronoun_Reflexive = "themself";
    }

    public class Program
    {
        static Lazy<TestSettings> Settings = null!;

        public static string CapatalizeFirst(string text)
        {
            return string.Concat(text[0].ToString().ToUpper(), text.AsSpan(1));
        }

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        public static readonly FormLink<Global> Female = FormKey.Factory("000F48:Gender-Neutral Dialogue.esp").ToLink<Global>();
        public static readonly FormLink<Global> Male = FormKey.Factory("000F49:Gender-Neutral Dialogue.esp").ToLink<Global>();
        public static readonly FormLink<Keyword> NpcNonBinary = FormKey.Factory("EBDA00:Update.esm").ToLink<Keyword>();
        public static readonly FormLink<GlobalShort> CustomPronouns = FormKey.Factory("000F4A:Gender-Neutral Dialogue.esp").ToLink<GlobalShort>();

        public static bool IsValidDialogue(IDialogResponsesGetter response)
        {
            var returnTrue = false;
            if (response.Conditions != null)
            {
                foreach (var condition in response.Conditions)
                {
                    if (condition.Data != null)
                    {
                        var conditionFunction = (FunctionConditionData)condition.Data.DeepCopy();
                        if (conditionFunction.Function == Condition.Function.HasKeyword)
                        {
                            if (conditionFunction.ParameterOneRecord.FormKey.GetHashCode() == NpcNonBinary.FormKey.GetHashCode()) return false;
                        }
                        else if (conditionFunction.Function == Condition.Function.GetPCIsSex)
                        {
                            returnTrue = true;
                        }
                        else if (conditionFunction.Function == Condition.Function.GetIsSex && conditionFunction.RunOnType != Condition.RunOnType.Subject)
                        {
                            returnTrue = true;
                        }
                    }
                }
            }
            return returnTrue;
        }

        public static bool IsCustomDialogue(IDialogResponsesGetter response)
        {
            if (response.Conditions != null)
            {
                foreach (var condition in response.Conditions)
                {
                    if (condition.Data != null)
                    {
                        var conditionFunction = (FunctionConditionData)condition.Data.DeepCopy();
                        if (conditionFunction.Function == Condition.Function.GetGlobalValue)
                        {
                            if (conditionFunction.ParameterOneRecord.FormKey == CustomPronouns.FormKey)
                            {
                                return true;
                            }
                        }
                    }
                }
            }
            return false;
        }

        public static bool TryCreateAlias(string textToReplace, string aliasName, FormKey reference, List<QuestAlias> aliases, string text, uint aliasID, out string newtext)
        {
            newtext = text.Replace(textToReplace, "<Alias=" + aliasName + ">");
            if (!text.Contains(textToReplace)) return false;
            aliasID += 1;
            aliases.Add(new QuestAlias()
            {
                Name = aliasName,
                ForcedReference = reference.ToNullableLink<IPlacedGetter>(),
                ID = aliasID,
                Flags = QuestAlias.Flag.StoresText
            });
            return true;
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            //Your code here!

            foreach (var item in state.LoadOrder.PriorityOrder.DialogResponses().WinningContextOverrides(state.LinkCache))
            {
                if (IsValidDialogue(item.Record))
                {
                    var responses = item.GetOrAddAsOverride(state.PatchMod);
                    string? responsetext = "";
                    if (responses.Responses.TryGet(0, out var output))
                    {
                        responsetext = output.Text;
                    }
                    Console.WriteLine(item.ModKey.FileName + " " + responses.FormKey + " " + responsetext);

                    responses.Flags ??= new();
                    responses.Flags.Flags |= DialogResponses.Flag.Random;

                    var index = 0;
                    foreach (var condition in responses.Conditions)
                    {
                        if (condition.Data == null) continue;
                        var conditionFunction = (FunctionConditionData)condition.Data;
                        if (conditionFunction.Function == Condition.Function.GetPCIsSex)
                        {
                            if ((conditionFunction.ParameterOneNumber == 0 && condition.CompareOperator == CompareOperator.EqualTo) || (conditionFunction.ParameterOneNumber == 1 && condition.CompareOperator == CompareOperator.NotEqualTo))
                            {
                                responses.Conditions.Remove(condition);
                                responses.Conditions.Insert(index, new ConditionFloat()
                                {
                                    CompareOperator = CompareOperator.EqualTo,
                                    ComparisonValue = 1,
                                    Data = new FunctionConditionData()
                                    {
                                        Function = Condition.Function.GetGlobalValue,
                                        ParameterOneRecord = Female
                                    }
                                });
                            }
                            else if ((conditionFunction.ParameterOneNumber == 1 && condition.CompareOperator == CompareOperator.EqualTo) || (conditionFunction.ParameterOneNumber == 0 && condition.CompareOperator == CompareOperator.NotEqualTo))
                            {
                                responses.Conditions.Remove(condition);
                                responses.Conditions.Insert(index, new ConditionFloat()
                                {
                                    CompareOperator = CompareOperator.EqualTo,
                                    ComparisonValue = 1,
                                    Data = new FunctionConditionData()
                                    {
                                        Function = Condition.Function.GetGlobalValue,
                                        ParameterOneRecord = Male
                                    }
                                });
                            }
                            break;
                        }
                        else if (conditionFunction.Function == Condition.Function.GetIsSex && conditionFunction.RunOnType != Condition.RunOnType.Subject)
                        {
                            if (conditionFunction.Reference.FormKey == Constants.Player.FormKey)
                            {
                                if ((conditionFunction.ParameterOneNumber == 0 && condition.CompareOperator == CompareOperator.EqualTo) || (conditionFunction.ParameterOneNumber == 1 && condition.CompareOperator == CompareOperator.NotEqualTo))
                                {
                                    responses.Conditions.Remove(condition);
                                    responses.Conditions.Insert(index, new ConditionFloat()
                                    {
                                        CompareOperator = CompareOperator.EqualTo,
                                        ComparisonValue = 1,
                                        Data = new FunctionConditionData()
                                        {
                                            Function = Condition.Function.GetGlobalValue,
                                            ParameterOneRecord = Female
                                        }
                                    });
                                }
                                else if ((conditionFunction.ParameterOneNumber == 1 && condition.CompareOperator == CompareOperator.EqualTo) || (conditionFunction.ParameterOneNumber == 0 && condition.CompareOperator == CompareOperator.NotEqualTo))
                                {
                                    responses.Conditions.Remove(condition);
                                    responses.Conditions.Insert(index, new ConditionFloat()
                                    {
                                        CompareOperator = CompareOperator.EqualTo,
                                        ComparisonValue = 1,
                                        Data = new FunctionConditionData()
                                        {
                                            Function = Condition.Function.GetGlobalValue,
                                            ParameterOneRecord = Male
                                        }
                                    });
                                }
                            }
                            else
                            {
                                responses.Conditions.Insert(index + 1, new ConditionFloat()
                                {
                                    CompareOperator = CompareOperator.EqualTo,
                                    ComparisonValue = 0,
                                    Data = new FunctionConditionData()
                                    {
                                        Function = Condition.Function.HasKeyword,
                                        RunOnType = conditionFunction.RunOnType,
                                        ParameterOneRecord = NpcNonBinary,
                                    }
                                });
                                responses.Conditions.Insert(index, new ConditionFloat() // is player
                                {
                                    Flags = Condition.Flag.OR,
                                    CompareOperator = CompareOperator.EqualTo,
                                    ComparisonValue = 1,
                                    Data = new FunctionConditionData()
                                    {
                                        Function = Condition.Function.GetIsID,
                                        RunOnType = conditionFunction.RunOnType,
                                        ParameterOneRecord = Skyrim.Npc.Player,
                                    }
                                });
                                responses.Conditions.Insert(index, new ConditionFloat() // not player
                                {
                                    CompareOperator = CompareOperator.EqualTo,
                                    ComparisonValue = 0,
                                    Data = new FunctionConditionData()
                                    {
                                        Function = Condition.Function.GetIsID,
                                        RunOnType = conditionFunction.RunOnType,
                                        ParameterOneRecord = Skyrim.Npc.Player
                                    }
                                });
                                if ((conditionFunction.ParameterOneNumber == 0 && condition.CompareOperator == CompareOperator.EqualTo) || (conditionFunction.ParameterOneNumber == 1 && condition.CompareOperator == CompareOperator.NotEqualTo))
                                {
                                    responses.Conditions.Insert(index, new ConditionFloat()
                                    {
                                        Flags = Condition.Flag.OR,
                                        CompareOperator = CompareOperator.EqualTo,
                                        ComparisonValue = 1,
                                        Data = new FunctionConditionData()
                                        {
                                            Function = Condition.Function.GetGlobalValue,
                                            ParameterOneRecord = Female
                                        }
                                    });
                                }
                                else
                                {
                                    responses.Conditions.Insert(index, new ConditionFloat()
                                    {
                                        Flags = Condition.Flag.OR,
                                        CompareOperator = CompareOperator.EqualTo,
                                        ComparisonValue = 1,
                                        Data = new FunctionConditionData()
                                        {
                                            Function = Condition.Function.GetGlobalValue,
                                            ParameterOneRecord = Male
                                        }
                                    });
                                }
                            }
                            break;
                        }
                        index++;
                    }
                }
                else if (Settings.Value.PatchCustomPronouns && IsCustomDialogue(item.Record))
                {
                    var responses = item.GetOrAddAsOverride(state.PatchMod);

                    foreach (var response in responses.Responses)
                    {
                        string? text = response.Text.String ?? throw new Exception("Null text for dialogue response");
                        text = text.Replace("&&p_Nominative&&", Settings.Value.CustomPronoun_Nominative);
                        text = text.Replace("&&P_Nominative&&", CapatalizeFirst(Settings.Value.CustomPronoun_Nominative));
                        text = text.Replace("&&p_Accusative&&", Settings.Value.CustomPronoun_Accusative);
                        text = text.Replace("&&P_Accusative&&", CapatalizeFirst(Settings.Value.CustomPronoun_Accusative));
                        text = text.Replace("&&p_Reflexive&&", Settings.Value.CustomPronoun_Reflexive);
                        text = text.Replace("&&P_Reflexive&&", CapatalizeFirst(Settings.Value.CustomPronoun_Reflexive));
                        text = text.Replace("&&p_Possessive&&", Settings.Value.CustomPronoun_PronominalPossessive);
                        text = text.Replace("&&P_Possessive&&", CapatalizeFirst(Settings.Value.CustomPronoun_PronominalPossessive));

                        response.Text = text;
                        Console.WriteLine(text);
                    }
                }
            }

            foreach (var questGetter in state.LoadOrder.PriorityOrder.Quest().WinningOverrides())
            {
                List<QuestAlias> aliases = new();
                bool overriden = false;
                uint maxAliasID = 0;
                foreach (var aliasGetter in questGetter.Aliases)
                {
                    if (aliasGetter.ID > maxAliasID) maxAliasID = aliasGetter.ID;
                }
                foreach (var aliasGetter in questGetter.Aliases)
                {
                    Book? book = null;
                    if (aliasGetter.CreateReferenceToObject == null) continue;
                    if (aliasGetter.CreateReferenceToObject.Object.TryResolve<IBookGetter>(state.LinkCache, out var bookGetter))
                    {
                        if (bookGetter.Teaches is BookSpell) continue;
                        book = bookGetter.DeepCopy();
                    }
                    if (book != null)
                    {
                        string text = book.BookText.ToString();
                        if (text == null) continue;

                        //if (TryCreateAlias("<Alias.Pronoun=Player>", "They", FormKey.Factory("000FD5:Gender-Neutral Dialogue.esp"), aliases, text, maxAliasID, out var newtext))

                        if (text.Contains("<Alias.PronounPos=Player>"))
                        {
                            text = text.Replace("<Alias.PronounPos=Player>", "<Alias=theirs>");
                            if (!aliases.Any(alias => alias.Name == "theirs"))
                            {
                                maxAliasID += 1;
                                aliases.Add(new QuestAlias()
                                {
                                    Name = "theirs",
                                    ForcedReference = FormKey.Factory("0008C7:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                    Flags = QuestAlias.Flag.StoresText,
                                    ID = maxAliasID
                                });
                            }
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounPosCap=Player>"))
                        {
                            text = text.Replace("<Alias.PronounPosCap=Player>", "<Alias=Theirs>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "Theirs",
                                ForcedReference = FormKey.Factory("000B52:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounObj=Player>"))
                        {
                            text = text.Replace("<Alias.PronounObj=Player>", "<Alias=them>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "them",
                                ForcedReference = FormKey.Factory("0008C5:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounObjCap=Player>"))
                        {
                            text = text.Replace("<Alias.PronounObjCap=Player>", "<Alias=Them>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "Them",
                                ForcedReference = FormKey.Factory("000B51:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounInt=Player>"))
                        {
                            text = text.Replace("<Alias.PronounInt=Player>", "<Alias=themself>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "themself",
                                ForcedReference = FormKey.Factory("0008C8:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounIntCap=Player>"))
                        {
                            text = text.Replace("<Alias.PronounIntCap=Player>", "<Alias=Themself>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "Themself",
                                ForcedReference = FormKey.Factory("000B32:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounRef=Player>"))
                        {
                            text = text.Replace("<Alias.PronounRef=Player>", "<Alias=themself>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "themself",
                                ForcedReference = FormKey.Factory("0008C8:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounRefCap=Player>"))
                        {
                            text = text.Replace("<Alias.PronounRefCap=Player>", "<Alias=Themself>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "Themself",
                                ForcedReference = FormKey.Factory("000B32:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounPosObj=Player> does"))
                        {
                            text = text.Replace("<Alias.PronounPosObj=Player> does", "<Alias=their>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "their",
                                ForcedReference = FormKey.Factory("0008C6:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounPosObjCap=Player> does"))
                        {
                            text = text.Replace("<Alias.PronounPosObjCap=Player> does", "<Alias=Their>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "Their",
                                ForcedReference = FormKey.Factory("0008D1:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player>'s"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player>'s", "<Alias=they've>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they've",
                                ForcedReference = FormKey.Factory("0008C9:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player>'s"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player>'s", "<Alias=They've>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "They've",
                                ForcedReference = FormKey.Factory("000B53:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player> is"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player> is", "<Alias=they are>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they are",
                                ForcedReference = FormKey.Factory("000FD6:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player> is"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player> are", "<Alias=They are>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "They are",
                                ForcedReference = FormKey.Factory("0008CB:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player> reaches"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player> reaches", "<Alias=they reach>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they reach",
                                ForcedReference = FormKey.Factory("0008D2:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player> reaches"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player> reaches", "<Alias=They reach>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they reach",
                                ForcedReference = FormKey.Factory("0008D3:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player> does"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player> does", "<Alias=they do>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they do",
                                ForcedReference = FormKey.Factory("0008CF:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player> does"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player> does", "<Alias=They do>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "They do",
                                ForcedReference = FormKey.Factory("0008D0:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player> calls"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player> calls", "<Alias=they call>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they call",
                                ForcedReference = FormKey.Factory("0008D0:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player> calls"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player> calls", "<Alias=They call>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "They call",
                                ForcedReference = FormKey.Factory("0008CE:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player> was"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player> was", "<Alias=they were>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they were",
                                ForcedReference = FormKey.Factory("000FD7:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player> was"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player> was", "<Alias=They were>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "They were",
                                ForcedReference = FormKey.Factory("0008CA:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.Pronoun=Player>"))
                        {
                            text = text.Replace("<Alias.Pronoun=Player>", "<Alias=they>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "they",
                                ForcedReference = FormKey.Factory("000FD5:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }
                        if (text.Contains("<Alias.PronounCap=Player>"))
                        {
                            text = text.Replace("<Alias.PronounCap=Player>", "<Alias=They>");
                            maxAliasID += 1;
                            aliases.Add(new QuestAlias()
                            {
                                Name = "They",
                                ForcedReference = FormKey.Factory("0008CC:Gender-Neutral Dialogue.esp").ToNullableLink<IPlacedGetter>(),
                                Flags = QuestAlias.Flag.StoresText,
                                ID = maxAliasID
                            });
                            overriden = true;
                        }

                        if (overriden)
                        {
                            book.BookText = text;
                            state.PatchMod.Books.Set(book);
                            Console.WriteLine(/*book.ModKey.FileName + " " + */book.FormKey + " " + book.EditorID + Environment.NewLine + text);
                        }
                    }
                }
                if (overriden)
                {
                    var quest = questGetter.DeepCopy();
                    quest.Aliases.Add(aliases);
                    state.PatchMod.Quests.Set(quest);
                }
            }

            /*
            if (Settings.Value.PatchBookText)
            {
                foreach (var item in state.LoadOrder.PriorityOrder.Book().WinningContextOverrides())
                {
                    var text = item.Record.BookText.ToString();
                    if (text == null) continue;
                    if (text.Contains("<Alias.Pronoun=Player>") || text.Contains("<Alias.PronounObj=Player>") || text.Contains("<Alias.PronounPos=Player>") || text.Contains("<Alias.PronounPosObj=Player>") || text.Contains("<Alias.PronounRef=Player>") || text.Contains("<Alias.PronounInt=Player>") || text.Contains("<Alias.PronounCap=Player>") || text.Contains("<Alias.PronounObjCap=Player>") || text.Contains("<Alias.PronounPosCap=Player>") || text.Contains("<Alias.PronounPosObjCap=Player>") || text.Contains("<Alias.PronounRefCap=Player>") || text.Contains("<Alias.PronounIntCap=Player>"))
                    {
                        var book = item.GetOrAddAsOverride(state.PatchMod);

                        if (Settings.Value.PatchCustomPronouns)
                        {
                            text = text.Replace("<Alias.Pronoun=Player>", Settings.Value.CustomPronoun_Nominative);
                            text = text.Replace("<Alias.PronounCap=Player>", CapatalizeFirst(Settings.Value.CustomPronoun_Nominative));
                            text = text.Replace("<Alias.PronounObj=Player>", Settings.Value.CustomPronoun_Accusative);
                            text = text.Replace("<Alias.PronounObjCap=Player>", CapatalizeFirst(Settings.Value.CustomPronoun_Accusative));
                            text = text.Replace("<Alias.PronounPosObj=Player>", Settings.Value.CustomPronoun_PronominalPossessive);
                            text = text.Replace("<Alias.PronounPosObjCap=Player>", CapatalizeFirst(Settings.Value.CustomPronoun_PronominalPossessive));
                            text = text.Replace("<Alias.PronounPos=Player>", Settings.Value.CustomPronoun_PredicativePossessive);
                            text = text.Replace("<Alias.PronounPosCap=Player>", CapatalizeFirst(Settings.Value.CustomPronoun_PredicativePossessive));
                            text = text.Replace("<Alias.PronounRef=Player>", Settings.Value.CustomPronoun_Reflexive);
                            text = text.Replace("<Alias.PronounRefCap=Player>", CapatalizeFirst(Settings.Value.CustomPronoun_Reflexive));
                            text = text.Replace("<Alias.PronounInt=Player>", Settings.Value.CustomPronoun_Reflexive);
                            text = text.Replace("<Alias.PronounIntCap=Player>", CapatalizeFirst(Settings.Value.CustomPronoun_Reflexive));
                        }
                        else
                        {
                            text = text.Replace("<Alias.Pronoun=Player> is", "they are");
                            text = text.Replace("<Alias.PronounCap=Player> is", "They are");
                            text = text.Replace("<Alias.Pronoun=Player> was", "they were");
                            text = text.Replace("<Alias.PronounCap=Player> was", "They were");
                            text = text.Replace("<Alias.Pronoun=Player> reaches", "they reach");
                            text = text.Replace("<Alias.PronounCap=Player> reaches", "They reach");
                            text = text.Replace("<Alias.Pronoun=Player> calls", "they call");
                            text = text.Replace("<Alias.PronounCap=Player> calls", "They call");
                            text = text.Replace("<Alias.Pronoun=Player> does", "they do");
                            text = text.Replace("<Alias.PronounCap=Player> does", "They do");
                            text = text.Replace("<Alias.Pronoun=Player>'s", "they've");
                            text = text.Replace("<Alias.PronounCap=Player>'s", "They've");
                            text = text.Replace("<Alias.Pronoun=Player>", "they");
                            text = text.Replace("<Alias.PronounCap=Player>", "They");
                            text = text.Replace("<Alias.PronounObj=Player>", "them");
                            text = text.Replace("<Alias.PronounObjCap=Player>", "Them");
                            text = text.Replace("<Alias.PronounPosObj=Player>", "their");
                            text = text.Replace("<Alias.PronounPosObjCap=Player>", "Their");
                            text = text.Replace("<Alias.PronounPos=Player>", "theirs");
                            text = text.Replace("<Alias.PronounPosCap=Player>", "Theirs");
                            text = text.Replace("<Alias.PronounRef=Player>", "themself");
                            text = text.Replace("<Alias.PronounRefCap=Player>", "Themself");
                            text = text.Replace("<Alias.PronounInt=Player>", "themself");
                            text = text.Replace("<Alias.PronounIntCap=Player>", "Themself");
                        }

                        book.BookText = text;
                        Console.WriteLine(item.ModKey.FileName + " " + book.FormKey + " " + book.EditorID + Environment.NewLine + text);
                    }
                }
            }
            */
        }
    }
}
